development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: msrs_development
  pool: 5
  username: msrs_user
  password: ILoveMusic@2018
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: msrs_test
  pool: 5
  username: koyama
  password: ilovemusic
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
